# Generated by Django 5.1.7 on 2025-03-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spotifytoken',
            unique_together=set(),
        ),
    ]
